/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kitchencodersrms;

import java.sql.Connection;
import javax.swing.DefaultListModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author williammcclain
 */
public class Employees extends javax.swing.JFrame {

    
    Connection c = null;
    ResultSet rs = null;
    Statement stmt;
    /**
     * Creates new form Employees
     */
    public Employees() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        addBOHButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        employeeFOHList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        employeeBOHList = new javax.swing.JList<>();
        modBOHButton = new javax.swing.JButton();
        removeBOHButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        removeFOHButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        addFOHButton = new javax.swing.JButton();
        modFOHButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Front of House");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        addBOHButton.setText("Add");
        addBOHButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBOHButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Back of House");

        employeeFOHList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(employeeFOHList);

        employeeBOHList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(employeeBOHList);

        modBOHButton.setText("Modify");
        modBOHButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modBOHButtonActionPerformed(evt);
            }
        });

        removeBOHButton.setText("Remove");
        removeBOHButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBOHButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Functions");

        removeFOHButton.setText("Remove");
        removeFOHButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFOHButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Functions");

        addFOHButton.setText("Add");
        addFOHButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFOHButtonActionPerformed(evt);
            }
        });

        modFOHButton.setText("Modify");
        modFOHButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modFOHButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(215, 215, 215))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(modFOHButton, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(removeFOHButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(addFOHButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(addBOHButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modBOHButton, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(17, 17, 17)))
                    .addComponent(removeBOHButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(addFOHButton)
                        .addGap(18, 18, 18)
                        .addComponent(modFOHButton)
                        .addGap(18, 18, 18)
                        .addComponent(removeFOHButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(addBOHButton)
                        .addGap(18, 18, 18)
                        .addComponent(modBOHButton)
                        .addGap(18, 18, 18)
                        .addComponent(removeBOHButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    DefaultListModel DM = new DefaultListModel();
    DefaultListModel DM2 = new DefaultListModel();

    private void addFOH(String names){
        employeeFOHList.setModel(DM);
        DM.addElement(names);
    }
    
        private void addBOH(String names){
        employeeBOHList.setModel(DM2);
        DM2.addElement(names);
    }
    

    
    private void addFOHButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFOHButtonActionPerformed
                        dispose();
                        NewEmployee s = new NewEmployee();                  
                        s.setVisible(true);                                        
    }//GEN-LAST:event_addFOHButtonActionPerformed

    private void addBOHButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBOHButtonActionPerformed
                        dispose();
                        NewEmployeeBOH s = new NewEmployeeBOH();                  
                        s.setVisible(true);         
    }//GEN-LAST:event_addBOHButtonActionPerformed

    private void modBOHButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modBOHButtonActionPerformed
        if(!employeeBOHList.isSelectionEmpty()){
            String selected = employeeBOHList.getSelectedValue();
            if(!selected.isEmpty()){
                    c = KitchenCodersRMS.callDatbase();
                    Employee editEmployee = new Employee();
                    editEmployee.sendName(selected);
                    editEmployee.setVisible(true);
                    this.dispose();
            }  
        }else{
            JOptionPane.showMessageDialog(null, "Please select employee to modify info");
        }                 
    }//GEN-LAST:event_modBOHButtonActionPerformed

    private void modFOHButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modFOHButtonActionPerformed
        if(!employeeFOHList.isSelectionEmpty()){
            String selected = employeeFOHList.getSelectedValue();
            if(!selected.isEmpty()){
                    Employee editEmployee = new Employee();
                    editEmployee.sendName(selected);
                    editEmployee.setVisible(true);
                    this.dispose();
            }  
        }else{
            JOptionPane.showMessageDialog(null, "Please select employee to modify info");
        }
    }//GEN-LAST:event_modFOHButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
                // TODO add your handling code here:
        c = KitchenCodersRMS.callDatbase();
        try {
            stmt = c.createStatement();
            rs = stmt.executeQuery("SELECT * FROM Employee WHERE FOH=1");
            while(rs.next()){
                String nameFOH = rs.getString("firstname");
                nameFOH += " ";
                nameFOH += rs.getString("lastname");
                addFOH(nameFOH);

            }
        } catch (SQLException ex) {
            Logger.getLogger(Inventory.class.getName()).log(Level.SEVERE, null, ex);
        }
            try {
            stmt = c.createStatement();
            rs = stmt.executeQuery("SELECT * FROM Employee WHERE BOH=1");
            while(rs.next()){
                String nameBOH = rs.getString("firstname");
                nameBOH += " ";
                nameBOH += rs.getString("lastname");
                addBOH(nameBOH);

            }
        } catch (SQLException ex) {
            Logger.getLogger(Inventory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void removeFOHButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFOHButtonActionPerformed
        String selected = employeeFOHList.getSelectedValue();
        String firstName = selected.substring(0, selected.indexOf(" "));
        String lastName = selected.substring(selected.indexOf(" ") + 1);
        if(!selected.isEmpty()){
            try {
                stmt = c.createStatement();
                String sql = "DELETE FROM Employee WHERE firstname='" + firstName + "' "
                        + "AND lastname='" + lastName + "'";
                stmt.executeUpdate(sql);
                
                int input = JOptionPane.showOptionDialog(null, "Employee removed", "Success", JOptionPane.DEFAULT_OPTION,
                JOptionPane.INFORMATION_MESSAGE, null, null, null);
                if(input == JOptionPane.OK_OPTION){
                     c.close();
                     dispose();
                     Employees s = new Employees();
                     s.setVisible(true);
                }     
            } catch (SQLException ex) {
                Logger.getLogger(Inventory.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_removeFOHButtonActionPerformed

    private void removeBOHButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBOHButtonActionPerformed
        String selected = employeeBOHList.getSelectedValue();
        String firstName = selected.substring(0, selected.indexOf(" "));
        String lastName = selected.substring(selected.indexOf(" ") + 1);
        if(!selected.isEmpty()){
            try {
                stmt = c.createStatement();
                String sql = "DELETE FROM Employee WHERE firstname='" + firstName + "' "
                        + "AND lastname='" + lastName + "'";
                stmt.executeUpdate(sql);
                
                int input = JOptionPane.showOptionDialog(null, "Employee removed", "Success", JOptionPane.DEFAULT_OPTION,
                JOptionPane.INFORMATION_MESSAGE, null, null, null);
                if(input == JOptionPane.OK_OPTION){
                     c.close();
                     dispose();
                     Employees s = new Employees();
                     s.setVisible(true);
                }     
            } catch (SQLException ex) {
                Logger.getLogger(Inventory.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_removeBOHButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
                        dispose();
                        ManagerMenu s = new ManagerMenu();                  
                        s.setVisible(true);           
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBOHButton;
    private javax.swing.JButton addFOHButton;
    private javax.swing.JList<String> employeeBOHList;
    private javax.swing.JList<String> employeeFOHList;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton modBOHButton;
    private javax.swing.JButton modFOHButton;
    private javax.swing.JButton removeBOHButton;
    private javax.swing.JButton removeFOHButton;
    // End of variables declaration//GEN-END:variables
}
